version: '3.8'

services:
  ubuntu:
    image: ubuntu:latest
    container_name: ubuntu-container
    # Keep container running
    command: tail -f /dev/null
    # Enable interactive mode
    stdin_open: true
    tty: true
    # Mount a volume for persistence
    volumes:
      - ./data:/data
    # Restart policy
    restart: unless-stopped
